### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Alvyre** [PierreChls/iSeason#5]
# TO DO LIST
## Scene
- [x] Make and read a config file
- [x] Manage Models, Shader Lights
## Lights
- [x] Point Light class
- [x] Directional Light class
- [x] SpotLight class
- [x] Light Shader
- [ ] Shadows & AA
- [ ] +++ Deferred Shading
## Texture
- [x] Load texture for models
## Worlds
- [x] Make the world in 3D and models
- [x] Make the skybox
- [x] Make 4 worlds (each seaon)
- [x] Use funny shaders (snow, colors, Special FX)
## Engine
- [x] Checkpoints --> #14 
- [x] Travel between checkpoints
- [x] Travel between worlds
- [x] Make the menu to navigate between the different words
## Music
- [x] Add a background music by season
- [x] Add music when the user click
## Other
- [ ] Clean the code
- [ ] Verify if methods need to be public or can moved in private
- [ ] Implements Google Tests and write test for the application (eXtreme Programming)
